### ISSUE TITLE
Error with email notification (looking in the wrong folder)

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/mentions#25]
Twig is looking in the wrong folder. I really don't know why, cause this is a language file.
Have to check that.

```
[19-Mar-2015 09:34:32 Europe/Rome] PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "mention.txt" (looked into: ./ext/wolfsblvt/mentions/styles/all/template, ./ext/wolfsblvt/mentions/styles/all/theme).' in C:\Apache Software Foundation\Apache2.2\htdocs\MyForum\vendor\twig\twig\lib\Twig\Loader\Filesystem.php:202
Stack trace:
#0 C:\Apache Software Foundation\Apache2.2\htdocs\MyForum\phpbb\template\twig\loader.php(106): Twig_Loader_Filesystem->findTemplate('@wolfsblvt_ment...')
#1 C:\Apache Software Foundation\Apache2.2\htdocs\MyForum\vendor\twig\twig\lib\Twig\Loader\Filesystem.php(138): phpbb\template\twig\loader->findTemplate('@wolfsblvt_ment...')
#2 C:\Apache Software Foundation\Apache2.2\htdocs\MyForum\vendor\twig\twig\lib\Twig\Environment.php(265): Twig_Loader_Filesystem->getCacheKey('@wolfsblvt_ment...')
#3 C:\Apache Software Foundation\Apache2.2\htdocs\MyForum\vendor\twig\twig\lib\Twig\Environment.php(312): Twig_Environment->getTemplateClass('@wolfsblvt_ment...', NULL)
#4 C:\Apache Software F in C:\Apache Software Foundation\Apache2.2\htdocs\MyForum\vendor\twig\twig\lib\Twig\Loader\Filesystem.php on line 202
```

Bug was mentioned here: https://www.phpbb.com/community/viewtopic.php?p=14005331#p14005331

**Comment by iMattPro** [comment]
Try switching the slash in https://github.com/Wolfsblvt/mentions/blob/master/notification/mention.php#L178

**Comment by Wolfsblvt** [comment]
Thanks for the tip, I will do that.

**Comment by Wolfsblvt** [comment]
Thanks for reporting this and for using the project. This project is no longer maintained, so I’m closing all remaining issues as part of archiving the repository. This avoids leaving a false impression that further development or support is planned.

Anyone interested in continuing development is welcome to do so through a fork, subject to the repository’s license and any applicable third-party licenses.
